
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import BoardSidebar from "@/components/ui/boardSidebar";
import { BoardProvider } from "@/app/contexts/boardContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <BoardProvider>
            <div className="flex w-full">
              <BoardSidebar />
              <div className="flex flex-col flex-1">
                <main className="w-full">
                  {children}
                </main>
              </div>
            </div>
          </BoardProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}

